### ISSUE TITLE
Single commit?

### ISSUE THREAD

**Issue by Wandalen** [NataliaBondarenko/weather-aggregator#1]
More comfortable to work by your own? :)

**Comment by NataliaBondarenko** [comment]
I'm not the only one working

**Comment by Wandalen** [comment]
How did you collaborate?

**Comment by NataliaBondarenko** [comment]
Why are you asking?

**Comment by Wandalen** [comment]
Curious. 

Your tutor does what he does quite poorly. It doesn't matter WHAT you guys do at this stage of your career. Matter only HOW. At the end of your course, you all are not trained enough to work in a team. This is only what matters at this stage. Not the code.
